-- CreateEnum
CREATE TYPE "Capability" AS ENUM ('POS_CREATE', 'POS_READ', 'POS_UPDATE', 'POS_DELETE', 'CLIENTS_CREATE', 'CLIENTS_READ', 'CLIENTS_UPDATE', 'CLIENTS_ACTIVATE', 'CLIENTS_SUSPEND', 'CLIENTS_TERMINATE', 'CLIENTS_CONNECTION_TYPE_UPDATE', 'CLIENTS_STATIC_IP_ASSIGN', 'CLIENTS_STATIC_IP_RELEASE', 'SUBSCRIPTIONS_CREATE', 'SUBSCRIPTIONS_READ', 'SUBSCRIPTIONS_UPDATE', 'SUBSCRIPTIONS_TERMINATE', 'SUBSCRIPTIONS_RENEW', 'SUBSCRIPTIONS_UPGRADE', 'USAGE_LOGS_CREATE', 'USAGE_LOGS_READ', 'INVOICES_CREATE', 'INVOICES_READ', 'INVOICES_CANCEL', 'PAYMENTS_CREATE', 'PAYMENTS_READ', 'SERVICE_PLANS_CREATE', 'SERVICE_PLANS_READ', 'SERVICE_PLANS_UPDATE', 'SERVICE_PLANS_DELETE', 'STATIC_IP_CREATE', 'STATIC_IP_READ', 'STATIC_IP_UPDATE', 'STATIC_IP_DELETE', 'BANDWIDTH_POOL_READ', 'BANDWIDTH_POOL_UPDATE', 'USERS_CREATE', 'USERS_READ', 'USERS_UPDATE', 'USERS_ACTIVATE', 'USERS_DEACTIVATE', 'PPPOE_REQUESTS_CREATE', 'PPPOE_REQUESTS_READ', 'PPPOE_REQUESTS_APPROVE', 'PPPOE_REQUESTS_REJECT', 'AUDIT_LOGS_READ', 'SUSPENSION_HISTORY_READ');

-- AlterEnum
ALTER TYPE "UserRole" ADD VALUE 'SUB_ADMIN';

-- AlterTable
ALTER TABLE "subscriptions" ADD COLUMN     "original_bandwidth_mbps" DECIMAL(10,2);

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "capabilities" "Capability"[] DEFAULT ARRAY[]::"Capability"[];
